### PR TITLE
Python module and additional functions

### PR DESCRIPTION
**Pull request by tjgalvin**
I've had a first pass at making this a `pip` installable module so that the code does not have to have an explicitly set path. 

Distinct environment variables have also been added for each of the beam and jones hdf5 files. 

It looks like a lot of the logic is included as part of the `__main__` alongside the processing of the options. For the moment I have added a function to both the `lookup_beam.py` and `lookup_jones.py` files to return the beam for a given set of meta-data and on-sky positions. This will not write the files / results to disk, and does not touch the logic that would otherwise be called.

### CODE REVIEW

**Comment by johnsmorgan** [comment]
Hi Tim,

This all looks great. Couple of minor suggestions:
- fix typo in function docstring (change to "attenuation")
- add yourself as an author

We should probably put all the standard calls into functions, but that's a job for another day.

**Comment by tjgalvin** [comment]
I would be locked up without spell checl ;) I've added those suggestions. 

I have it on my list of things to do to try to refactor some things, which is a little more important now that it can be packaged as a module. For the moment though I need the larger system working before trying to do that.

**Comment by tjgalvin** [comment]
I also found a few bugs, some where me in my haste, and some where python 2 to 3 errors. I have tested this on python 3 now and it seems to be working as expected, but I have not tried this on python 2.

**Comment by johnsmorgan** [comment]
OK, one last request then I promise I'll approve. Could you please change your function names to

`gleamx_beam_lookup` and `gleamx_jones_lookup`

to

`beam_lookup_1d` and `jones_lookup_1d`

**Comment by tjgalvin** [comment]
I can do that, sure. But I make no guarantees about it being appropriate for uses other than the way I am using it in some of the gleam-x code :-)

**Pull request merged**
